FROM mcr.Microsoft.com/dotnet/sdk:8.0 AS build-env
#DOCKER path
WORKDIR /app			

#Copy everything from .csproj of this previous folder and past it into docker path
COPY *.csproj ./
#Run dotnet restore command to restore all of the packages
RUN dotnet restore

#copy everything from the soruce directory to destination directory
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.Microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet","CommandsService.dll" ]