apiVersion: v1
Kind: Service   # For deployment of Node port this should be service
metadata:  
  name: platformnpservice-srv
spec:
  type: NodePort
  selector: 
    app: platformservice
  ports: 
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80 