apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80          # Change from 80 to 8080
      targetPort: 8080     # Ensure the pod's container is accessible on port 8080
